---
# tasks file for roles/system_parame_optimization
- name: set server's timezone to shanghai
  timezone:
     name: Asia/Shanghai

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"