---
# tasks file for roles/system_parame_optimization
- name: install ntp
  yum:
    name: ntp
    state: present

- name: RedHat7 server startup load ntp
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "7"

- name: RedHat6 server startup load ntp
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_distribution_major_version == "6"