---
# tasks file for php_memcached
- name: create temp directory in remote server
  file: path={{ temp_memcached_dir }} state=directory

- name: copy and unzip php's memcached module to temp directory in remote server
  unarchive: src={{ memcached_name }} dest={{ temp_memcached_dir }}

- name: install memcached module
  shell: >
         cd {{ temp_memcached_dir }}/*/ && {{ php_home }}/bin/phpize && ./configure                                                                                                           
         --with-php-config={{ php_home }}/bin/php-config --disable-memcached-sasl --enable-memcached --enable-memcached-json &&                                                                            
         make && make install
  notify: add_memcached

- name: clean memcached install package
  file: path={{ temp_memcached_dir }} state=absent
