---
# tasks file for php_redis
- name: create temp directory in remote server
  file: path={{ temp_redis_dir }} state=directory

- name: copy and unzip php's redis module to temp directory in remote server 
  unarchive: src={{ redis_name }} dest={{ temp_redis_dir }}

- name: install redis module 
  shell: >
         cd {{ temp_redis_dir }}/*/ && {{ php_home }}/bin/phpize && ./configure
         --with-php-config={{ php_home }}/bin/php-config && make && make install
  notify: add_redis

- name: clean redis install package
  file: path={{ temp_redis_dir }} state=absent
