---
# tasks file for linux_os_baseline
- name: ignore subnet broadcast message and shutdown ip package redirect
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      net.ipv4.conf.all.accept_redirects = 0
    backup: yes
    marker: "Broadcast and Redirects repair"
  notify: reload sysctl
  tags: Broadcast_Redirect

- name: cancel password ... pam_unix.so...
  lineinfile: 
    path: /etc/pam.d/system-auth
    regexp: 'password.*pam_unix\.so'
    line: "  "
    backrefs: yes
    backup: yes
  tags: cancel_pam_unix

- name: copy common-auth
  copy: src=common-auth dest=/etc/pam.d/ backup=yes mode=0644

- name:  Password Strength meter and password min history
  blockinfile: 
    path: /etc/pam.d/system-auth
    block: |
        auth        required      pam_tally2.so deny=5 onerr=fail unlock_time=300
        password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok remember=8
        password required pam_cracklib.so retry=3 minlen=8 dcredit=-1 ucredit=-1 lcredit=-1 ocredit=0
    backup: yes
    marker: Log_retryPass_minhistory
  tags: password_strength

- name: cancel account login fail lock function in file /etc/pam.d/login
  lineinfile: 
    path: /etc/pam.d/login
    regexp: "^auth    required    pam_tally2.so    deny=5    onerr=fail    unlock_time=300"
    line: '#auth    required    pam_tally2.so    deny=5    onerr=fail    unlock_time=300'
    backrefs: yes
    backup: yes
  tags: cancel_account_login


- name: set password max available time
  lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MAX_DAYS*.*"
    line: PASS_MAX_DAYS   90
    backrefs: yes
    backup: yes

- name: set password min length
  lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MIN_LEN*.*"
    line: PASS_MIN_LEN    8
    backrefs: yes
    backup: yes

- name: root console access
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PermitRootLogin yes"
    line: PermitRootLogin no
    backrefs: yes
    backup: yes
  notify: restart_sshd
  tags: root_console


