---
# tasks file for configuration
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: RedHat.yml
  when: ansible_distribution == 'RedHat'