---
# tasks file for php_pthreads
- name: create temp directory in remote server
  file: path={{ temp_pthreads_dir }} state=directory

- name: copy and unzip pthreads package to temp directory in remote server
  unarchive: src={{ pthreads_name }} dest={{ temp_pthreads_dir }}

- name: install pthreads module
  shell: >
         cd {{ temp_pthreads_dir }}/*/ && {{ php_home }}/bin/phpize && ./configure 
         --enable-pthreads --with-php-config={{ php_home }}/bin/php-config && make && make install
  notify: add_pthreads

- name: clean pthreads package
  file: path={{ temp_pthreads_dir }} state=absent
