---
# handlers file for php
- name: include_php-fpm.d
  lineinfile: 
    path: "{{ config_path }}/php-fpm.conf"
    regexp: '^include=.*/php-fpm.d/\*\.conf'
    line: include={{ config_path }}/php-fpm.d/*.conf

- name: service_php-fpm
  service: name=php-fpm state=started enabled=yes

- name: systemctl_php-fpm
  shell: /usr/bin/systemctl daemon-reload && /usr/bin/systemctl enable php-fpm && /usr/bin/systemctl start php-fpm

