---
# handlers file for php
- name: include_php-fpm.d
  lineinfile: 
    dest: "{{ project_info.base_dir }}/{{ project_info.name }}-{{ project_info.version }}/etc/php-fpm.conf"
    regexp: '^include=.*/php-fpm.d/\*\.conf'
    line: include={{ project_info.base_dir }}/{{ project_info.name }}-{{ project_info.version }}/etc/php-fpm.d/*.conf

- name: systemctl_php-fpm
  shell: /usr/bin/systemctl daemon-reload && /usr/bin/systemctl enable php-fpm

